# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('leadImage', models.FileField(blank=True, null=True, upload_to=posts.models.upload_location)),
                ('content', models.TextField()),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('draft', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimeStamp', models.DateTimeField(auto_now=True)),
                ('publish', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile')),
            ],
            options={
                'ordering': ['-timeStamp', '-updatedTimeStamp'],
            },
        ),
    ]
