# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-19 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default=datetime.datetime(2017, 6, 19, 2, 28, 24, 486306, tzinfo=utc), max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='lang',
            field=models.CharField(default='default', max_length=120),
            preserve_default=False,
        ),
    ]
