# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-10 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
        ('posts', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserProfile'),
        ),
    ]
