# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-06-18 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import projs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectPicture', models.ImageField(blank=True, null=True, upload_to=projs.models.upload_location)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug')),
                ('description', models.TextField()),
                ('github', models.URLField(blank=True, default='')),
                ('members', models.URLField(blank=True, default='')),
                ('category', models.CharField(max_length=120)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
